rgname                 = "stage-piyush-rg"
service_principal_name = "stage-piyush-spn"
keyvault_name          = "stage-piyush-kv-101"
SUB_ID = "9e9c27ce-e0c8-4171-a368-ad16977ec849"
node_pool_name = "stagenp"
cluster_name = "stage-piyush-cluster"